### ISSUE TITLE
SLFIP-1: Time starts running faster after starting a new game

### ISSUE THREAD

**Issue by Bentley386** [stelynx/fifteen-puzzle#1] opened 2020-10-25 14:57 UTC
On Android (8.0.0) starting a new game (tapping "+" in the game screen) causes the time to run faster in the following game.

**Comment by campovski** [comment] 2020-10-25 16:19
@Bentley386 Thank you for submitting a bug. The problem is that starting a new game while playing does not cancel the previous timer, therefore the timers keep stacking after each new game started from game screen. This issue will be resolved in the next version, until then, please do not start a new game while playing another one.

**Closed as completed** 2020-10-25 18:19 UTC
Labels: bug
